name: GEDI Test

# Specifies when the action should run
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

# Specifies the jobs that are to be run
jobs:
  test_feature_extraction:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install local package
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Set PYTHONPATH for tests
      run: |
        echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Run test
      run:
        pytest -v tests/test_feature_extraction.py --maxfail=1 --disable-warnings -q

  test_generation:
    runs-on: ubuntu-latest
    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install local package
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Set PYTHONPATH for tests
      run: |
        echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Run test
      run:
        pytest -v tests/test_generator.py --maxfail=1 --disable-warnings -q

  test_evaluation-plotter:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        sudo apt-get install build-essential python3 python3-dev

    - name: Install as local package
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run test
      run:
        python main.py -a config_files/pipeline_steps/evaluation_plotter.json

  test_main_integration:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        sudo apt-get install build-essential python3 python3-dev

    - name: Install as local package
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run test
      run:
        python main.py -a config_files/test/experiment_test.json